---
title: "2020 Complaints - Jayde Lyon"
output: html_document
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(janitor)

```

## 2020 Consumer Complaints


Column {data-width=650}
-----------------------------------------------------------------------

### Top 5 Companies with Most Complaints in 2020

```{r}
top5_complaints <- most_complaints %>% 
  top_n(5)

top5_complaints_chart <- plot_ly(data= top5_complaints, x = ~company, y = ~n, type = 'bar') %>% 
  layout(title = "Most Complaints in 2020",
         xaxis = list(title = "Company"),
         yaxis = list (title = "Number of Complaints"))

top5_complaints_chart
```

Column {data-width=350}
-----------------------------------------------------------------------

### Correlation Between Issues and the Company Saying it is Isolated

```{r}

isolated <- complaints %>% 
  filter(company_public_response == 'Company believes complaint is the result of an isolated error') 


isolated

isolated_chart <- plot_ly(data = isolated, x = ~issue, y = ~company_public_response,
        marker = list(size = 10,
                             color = 'blue',
                             line = list(color = 'blue',
                                         width = .5))) %>% 
  layout(title = "Issue v. Isolated Error",
         xaxis = list(title = "Issue"),
         yaxis = list (title = "Number of Complaints"))

isolated_chart

```

### Chart C

```{r}

covid_complaint_months <- complaints %>% 
  filter(str_detect(consumer_complaint_narrative, variations)) %>% 
  count(mm_yy_sent_to_company)

covid_complaint_months

covid_complaint_chart <- plot_ly(data= covid_complaint_months, x = ~mm_yy_sent_to_company, y = ~n, type = 'bar') %>% 
  layout(title = "Covid Related Complaints",
         xaxis = list(title = "Month Sent"),
         yaxis = list (title = "Number of Complaints"))

covid_complaint_chart

```

