---
title: "Initial Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
```


Loading the data and looking at it to see what I might want to look at 

```{r}

complaints <- readRDS('complaints.rds')

View(complaints)

```


First trend - most complaints

```{r}

# All of the data is from the year 2020

most_complaints <- complaints %>% 
 count(company) %>% 
  arrange(desc(n))

most_complaints

#interesting that the top 3 companies w/ the most complaints are substantially more

most_complaint_company<- complaints %>% 
  filter(company == c('Experian Information Solutions Inc.', 'TRANSUNION INTERMEDIATE HOLDINGS, INC.', 'EQUIFAX, INC.'))

```


Second trend

```{r}

# As noted in my second commit, is it more newsworthy that the top three tended to not give public responses - or the fewer that did

most_complaint_company %>% 
  count(company_public_response)

most_complaint_company %>% 
  filter(company_public_response == 'Company believes it acted appropriately as authorized by contract or law')

most_complaint_company %>% 
  count(company_response_to_consumer)

complaints %>% 
  count(company_public_response) %>% 
  arrange(desc(n))


```

I kind of went off on a tangent here

```{r}

complaints %>% 
  filter(company_public_response == 'Company believes complaint is the result of an isolated error') %>% 
  count(issue, company) %>% 
  arrange(desc(n))

#above could be interesting because although saying isolate incident, the top issues are common and not isolated within the single company 

head(complaints)

complaints %>% 
  select(issue, sub_issue, consumer_complaint_narrative, company_public_response, company) %>% 
  filter(company_public_response == 'Company believes complaint is the result of an isolated error', company == 'Shellpoint Partners, LLC', 
         issue == 'Trouble during payment process')

complaints %>% 
  select(issue, sub_issue, consumer_complaint_narrative, company_public_response, company) %>% 
  filter(company == 'Shellpoint Partners, LLC', 
         issue == 'Trouble during payment process') %>% 
  count(company_public_response) %>% 
  arrange(desc(n))

complaints %>% 
  filter(company == 'Shellpoint Partners, LLC') %>% 
  count(issue) %>% 
  arrange(desc(n))

```


Third trend - COVID 

```{r}

# Yes, this is tedious, however the str_to_lower isn't working for me. So, I will filter each one, name them and then combine

variations <- c('coronavirus', 'CORONAVIRUS', 'covid','COVID')

# complaints %>% 
#   select(consumer_complaint_narrative) %>% 
#   filter(str_detect(consumer_complaint_narrative, 'coronavirus'))
# 
# complaints %>% 
#   select(consumer_complaint_narrative) %>% 
#   filter(str_detect(consumer_complaint_narrative, 'CORONAVIRUS'))
# 
# complaints %>% 
#   select(consumer_complaint_narrative) %>% 
#   filter(str_detect(consumer_complaint_narrative, 'covid'))
# 
# complaints %>% 
#   select(consumer_complaint_narrative) %>% 
#   filter(str_detect(consumer_complaint_narrative, 'COVID'))

complaints %>% 
  filter(str_detect(consumer_complaint_narrative, variations))

```

